### ISSUE TITLE
wpi::ArrayRef<const char *> seems to be broken

### ISSUE THREAD

**Issue by virtuald** [robotpy/robotpy-wpiutil#18]
I believe what's happening is the str -> const char * caster is a temporary, so it gets destroyed, but the const char * is pointing at the temporary std::string.

Incidentally, this would apply to all of the STL list converters that pybind11 provides also.

**Comment by virtuald** [comment]
This would also break nested wpi::ArrayRef objects... don't ever do that though.

**Comment by auscompgeek** [comment]
Does this still happen now with `wpi::span`?

**Comment by virtuald** [comment]
It would... but I remember seeing some fixes in pybind11 at some point for char*. Let's close this for now.
