### ISSUE TITLE
DLL loading problem with wpiutil.dll

### ISSUE THREAD

**Issue by picode98** [robotpy/robotpy-wpiutil#8]
Seeing @virtuald 's [post](https://www.chiefdelphi.com/t/robotpy-2020-availability/369479/9), I gave it a try, and running the simulator throws an exception in robotpy-wpiutil when trying to open wpiutil.dll ("The specified module could not be found"); as far as I can tell with Sysinternals Process Monitor, this seems to be due to the missing dependency "VCRUNTIME140_1.dll". Am I missing an MSVC redistributable?

**Comment by ArchdukeTim** [comment]
From [here](https://answers.microsoft.com/en-us/windows/forum/windows_10-update/vcruntime140dll/b1a15b0e-e389-41a3-bc49-f4fc85bac575):
https://www.microsoft.com/en-us/download/details.aspx?id=52685

Give it a whirl?

**Comment by virtuald** [comment]
Yes, you would need the Visual Studio 2019 redistributable I think.

**Comment by picode98** [comment]
@virtuald Installing the Visual Studio 2019 redistributable resolved the problem. Thank you and @ArchdukeTim for the help.
